// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBq2dVBRFXKEea9aA67feuQV5XARAJ3gg',
    appId: '1:242727699649:web:248ab85a928452f8b40040',
    messagingSenderId: '242727699649',
    projectId: 'flutterproject-48bf4',
    authDomain: 'flutterproject-48bf4.firebaseapp.com',
    storageBucket: 'flutterproject-48bf4.appspot.com',
    measurementId: 'G-M4Z4FTEP2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiDCeHgpFKLzZO6s4fRVYETR1t2uD95a0',
    appId: '1:242727699649:android:7023d59f8793fc80b40040',
    messagingSenderId: '242727699649',
    projectId: 'flutterproject-48bf4',
    storageBucket: 'flutterproject-48bf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_edPUWbndb_M7kdNxAOBmSKZ8Y6Y19QA',
    appId: '1:242727699649:ios:d9d2fed790ef3dddb40040',
    messagingSenderId: '242727699649',
    projectId: 'flutterproject-48bf4',
    storageBucket: 'flutterproject-48bf4.appspot.com',
    iosBundleId: 'com.example.mechaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_edPUWbndb_M7kdNxAOBmSKZ8Y6Y19QA',
    appId: '1:242727699649:ios:d9d2fed790ef3dddb40040',
    messagingSenderId: '242727699649',
    projectId: 'flutterproject-48bf4',
    storageBucket: 'flutterproject-48bf4.appspot.com',
    iosBundleId: 'com.example.mechaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBq2dVBRFXKEea9aA67feuQV5XARAJ3gg',
    appId: '1:242727699649:web:c3bc6eb6f11cab87b40040',
    messagingSenderId: '242727699649',
    projectId: 'flutterproject-48bf4',
    authDomain: 'flutterproject-48bf4.firebaseapp.com',
    storageBucket: 'flutterproject-48bf4.appspot.com',
    measurementId: 'G-6GEB6SMTK2',
  );

}